version: "3.9"
services:
  web:
    container_name: "my-container_web"
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:5000"
    environment:
      FLASK_DEBUG: "true"

  redis:
    image: "redis:alpine"
    container_name: "my-container_redis"
    expose:
     - "6379"
     
    
